# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_auto_20170628_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('friend_id', models.CharField(max_length=255)),
                ('friend', models.ManyToManyField(related_name='friends', to='friend.Users')),
                ('user', models.ManyToManyField(related_name='users', to='friend.Users')),
            ],
        ),
    ]
