# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_auto_20170628_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('friend_id', models.CharField(max_length=255)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='friend.Users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='friend.Users')),
            ],
        ),
    ]
