# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0006_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend_id',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_id',
        ),
    ]
